import { createElement } from '@lwc/engine-dom';
import Spring26ReleaseLwcTest from 'c/spring26ReleaseLwcTest';

describe('c-spring26-release-lwc-test', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-spring26-release-lwc-test', {
            is: Spring26ReleaseLwcTest
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});